export const upcomingEvents=[
	// {
	// 	"date":"10/01/2016",
	// 	"event_title":"Rutgers TSA movie screening: 總鋪師",
	// 	"place":"Busch Student Center at Rutgers University",
	// 	"address":"604 Bartholomew Road, Piscataway, NJ 08854",
	// 	"details":"movie screening (總鋪師)",
	// 	"time_start":"11am",
	// 	"time_end":"2pm",
	// 	"contact1_title":"Rutgers TSA predsident",
	// 	"contact1":"Wen-Sen Lu",
	// 	"contact1_email":"rtsa2k15@gmail.com",
	// 	"contact2":"",
	// 	"contact2_email":"",
	// 	"icon":"glyphicon glyphicon-facetime-video",
	// 	"img":"Images/upcoming/總鋪師.jpg",
	// },
	// {
	// 	"date":"10/08/2016",
	// 	"event_title":"Princeton Outreach at Palmer Square",
	// 	"place":"Palmer square",
	// 	"address":"40 Nassau St. Princeton, New Jersey 08542",
	// 	"details":"Co-organized with OTD-NJ",
	// 	"time_start":"1pm",
	// 	"time_end":"3pm",
	// 	"contact1_title":"",
	// 	"contact1":"Tsai-Yen Han",
	// 	"contact1_email":"jane.han@gmail.com",
	// 	"contact2":"",
	// 	"contact2_email":"",
	// 	"icon":"glyphicon glyphicon-bullhorn",
	// 	"img":"Images/20160828/201608outreach-01.jpg",
	// },
	// {
	// 	"date":"10/08/2016",
	// 	"event_title":"Princeton tour and apple picking",
	// 	"place":"Princeton",
	// 	"address":"",
	// 	"details":"\n\t1:30pm - 3pm: TAA-NJ Princeton independence trails walking tour,\n\t3:30pm - 6pm: Terhune Farm Fuji apple picking",
	// 	"time_start":"1:30pm",
	// 	"time_end":"6pm",
	// 	"contact1_title":"current president",
	// 	"contact1":"Mark Kao",
	// 	"contact1_email":"lrmkao@gmail.com",
	// 	"contact2":"TAA-NJ",
	// 	"contact2_email":"taanjusa@gmail.com",
	// 	"icon":"glyphicon glyphicon-flag",
	// },
	// {
	// 	"date":"10/21/2016",
	// 	"event_title":"Rutgers TSA movie screening: 阿罩霧風雲",
	// 	"place":"Busch Student Center, Rome 116ABC",
	// 	"address":"604 Bartholomew Road, Piscataway, NJ 08854",
	// 	"details":"movie screening (阿罩霧風雲). 報名方式，請上網站。 <a href='https://goo.gl/forms/mS6FX4hJDndFVR7y2' target='_blank'>按我報名</a>",
	// 	"time_start":"7pm",
	// 	"time_end":"9pm",
	// 	"contact1_title":"Rutgers TSA predsident",
	// 	"contact1":"Wen-Sen Lu",
	// 	"contact1_email":"rtsa2k15@gmail.com",
	// 	"contact2":"",
	// 	"contact2_email":"",
	// 	"icon":"glyphicon glyphicon-facetime-video",
	// 	"img":"Images/upcoming/阿罩霧風雲.jpg",
	// },
	// {
	// 	"date":"10/23/2016",
	// 	"event_title":"Hiking's Best Season: Fall",
	// 	"place":"Near Bear Mountain",
	// 	"address":"",
	// 	"details":"\n\t9:15 am: 賞楓集合地點 1. Route 18 Sears Parking lot. We can car pool to Dunkin' Donuts (see below).\n\t11:00 am: 賞楓集合地點 2: Dunkin' Donuts，可以先在此上廁所，山上廁所不多。地址：59 Orange Turnpike, Sloatsburg, NY 10974。\n\t11:30 am - 4:00 pm: 七湖與熊山吃火鍋與賞楓:請多帶保暖的衣服或是自備熱飲。火鍋cost ~ $10 per person.\n\tOptional trips after Seven Lake hiking: Bear Mountain Oktoberfest - Self \n\t<a href='https://goo.gl/JtvLbs' target='_blank'>Click to see more detail</a>",
	// 	"time_start":"9:15 am",
	// 	"time_end":"4 pm",
	// 	"contact1_title":"current president",
	// 	"contact1":"Mark Kao",
	// 	"contact1_email":"lrmkao@gmail.com",
	// 	"contact2":"TAA-NJ",
	// 	"contact2_email":"taanjusa@gmail.com",
	// 	"icon":"glyphicon glyphicon-picture",
	// 	"img":"Images/20151025/miniwaska_03.jpg",
	// },
	// {
	// 	"date":"10/30/2016",
	// 	"event_title":"《52Hz, I love you》North American Tour, screening in New Jersey ",
	// 	"place":"Busch Student Center, Center Hall at Rutgers University",
	// 	"address":"604 Bartholomew Road, Piscataway, NJ 08854",
	// 	"details":"\n\t5:30 pm 入場, \n\t6:00-7:50pm 電影放映 (109 min), \n\t8:00-8:45 pm 魏德聖導演 speak about his vision through the films he directed, \n\t歡迎大家一起來欣賞魏德聖導演的新電影! 座位有限，想預訂電影票，請上網站。 \n\t<a href='http://ppt.cc/VdEqT' target='_blank'>按我報名</a>",
	// 	"time_start":"",
	// 	"time_end":"",
	// 	"contact1_title":"",
	// 	"contact1":"Tsai-Yen Han",
	// 	"contact1_email":"jane.han@gmail.com",
	// 	"contact2":"",
	// 	"contact2_email":"",
	// 	"icon":"glyphicon glyphicon-facetime-video",
	// 	"img":"Images/upcoming/50HzIOU.jpg",
	// },
	// {
	// 	"date":"11/04/2016",
	// 	"event_title":"林雨蒼：從開放資料到開放治理：台灣的努力",
	// 	"place":"Busch Student Center, Room 120ABC",
	// 	"address":"",
	// 	"details":"\n\tThe speaker(林雨蒼) is a member of '不當黨產委員會'.\n\tCo-sponsored by Rutgers TSA",
	// 	"time_start":"7:00pm",
	// 	"time_end":"9:00pm",
	// 	"contact1_title":"current president",
	// 	"contact1":"Mark Kao",
	// 	"contact1_email":"lrmkao@gmail.com",
	// 	"contact2":"TAA-NJ",
	// 	"contact2_email":"taanjusa@gmail.com",
	// 	"icon":"glyphicon glyphicon-user",
	// 	"img":"Images/upcoming/林雨蒼.jpeg"
	// },
	// {
	// 	"date":"11/05-06/2016",
	// 	"event_title":"NYC G0V hackathon",
	// 	"place":"WeWork Times Square",
	// 	"address":"1460 Broadway, New York, New York 10036",
	// 	"details":"\n\t紐約哲五 X 紐約G0V】「紐」轉台灣G0V黑客松。\n\t『不能沒有你！』\n\t你有著程式編碼的技術，並且渴望一展身手嗎？ \n\t你擁有UIUX與設計長才，想讓更多人看見嗎？\n\t你曾經發想許多讓這社會更好的創意創新點子，卻苦無夥伴一同實踐嗎？\n\t從紐約翻社會，從紐約轉台灣。\n\t紐約g0v黑客松邀請您與我們一起建立台灣、美國開放政府(Open Government)開放資料(Open Data)的交流平台，在紐約讓世界看到台灣，也讓台灣看見在美國的我們。\n\t「紐」轉台灣g0v黑客松需要你的參與。<a href='https://www.facebook.com/events/1254524254591614/' target='_blank'>Facebook</a> 更多報名資訊：<a href='http://www.g0vnyc.org/#/?_k=60liaq' target='_blank'>www.g0vnyc.org</a>",
	// 	"time_start":"Nov 4 at 7 PM ",
	// 	"time_end":"Nov 6 at 6 PM",
	// 	"contact1_title":"",
	// 	"contact1":"",
	// 	"contact1_email":"",
	// 	"contact2":"",
	// 	"contact2_email":"",
	// 	"icon":"glyphicon glyphicon-hourglass"
	// },

	// {
	// 	"date":"11/12/2016",
	// 	"event_title":"Rutgers TSA movie screening: 阿罩霧風雲 II：落子",
	// 	"place":"Busch Campus Center meeting room 117ABC",
	// 	"address":"604 Bartholomew Road, Piscataway, NJ 08854",
	// 	"details":"movie screening (阿罩霧風雲). 報名方式，請上網站。 <a href='https://goo.gl/forms/mS6FX4hJDndFVR7y2' target='_blank'>按我報名</a>",
	// 	"time_start":"12",
	// 	"time_end":"3 pm",
	// 	"contact1_title":"Rutgers TSA predsident",
	// 	"contact1":"Wen-Sen Lu",
	// 	"contact1_email":"rtsa2k15@gmail.com",
	// 	"contact2":"",
	// 	"contact2_email":"",
	// 	"icon":"glyphicon glyphicon-facetime-video",
	// 	"img":"Images/upcoming/阿罩霧風雲2.jpg",
	// },
	{
		"date":"12/2016",
		"event_title":"Princeton Outreach at Palmer Square",
		"place":"Palmer square",
		"address":"40 Nassau St. Princeton, New Jersey 08542",
		"details":"Co-organized with OTD-NJ",
		"time_start":"",
		"time_end":"",
		"contact1_title":"",
		"contact1":"Tsai-Yen Han",
		"contact1_email":"jane.han@gmail.com",
		"contact2":"",
		"contact2_email":"",
		"icon":"glyphicon glyphicon-bullhorn",
		"img":"Images/20161008/201610outreach-02.jpg"
	},

	]
